pipeline {
  agent any

  environment {
    APP_NAME = "votestream-backend"
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Install dependencies') {
      steps {
        dir('backend') {
          sh 'npm install'
        }
      }
    }

    stage('Build') {
      steps {
        dir('backend') {
          sh 'npm run build'
        }
      }
    }

    stage('Deploy') {
      steps {
        dir('backend') {
          sh '''
          pm2 describe $APP_NAME >/dev/null 2>&1 \
            && pm2 restart $APP_NAME \
            || pm2 start dist/server.js --name $APP_NAME
          pm2 save
          '''
        }
      }
    }
  }
}
